### ISSUE TITLE
Is there a way to submit a question on stackoverflow with RStackExchange package?

### ISSUE THREAD

**Issue by MarcinKosinski** [geoffjentry/RStackExchange#2]
I've seen `RStackExchange` package in this answer to [SO question](http://meta.stackexchange.com/questions/174972/stackoverflow-api-for-r). There are also links to other R packages that communicate with stackoverflow API. Did you consider using `RStackExchange` to submit a question on stackoverflow from R console?

**Comment by geoffjentry** [comment]
Hi - I honestly haven't even looked at this for 3+ years so it's hard to say what I did or didn't consider :) I think my intention was to allow for posting but when I put this together I had already seen from twitteR that people were more interested in data collection than data generation so perhaps not. 

My recollection was that this never completely worked and it's been so long now that I'd be very surprised if it still worked even to the degree that it used to.
